version: '3.8'
services:
  redis:
    build: ./redis
    container_name: redis
    image: redis
    ports: 
      - '6379:6379'
    expose:
      - 6379
  "web-application":
    build: "./web-application"
    ports:
      - "3000:8080"
      - "9229:9229"
    volumes:
      - "./web-application/src:/web-application/src"
    depends_on:
      - database
      - redis
    links: 
      - redis
    environment:
      - REDIS_URL=redis://redis
      #- COMPOSE_HTTP_TIMEOUT=200
  database:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=theRootPassword
      - MYSQL_DATABASE=webAppDatabase
  postgres:
    build: ./postgres_database
    container_name: postgres_database
    ports:
      - "5432:5432"
    image: insert_code_here_postgres_database
    environment:
      - POSTGRES_DB=postgresDatabase
      - POSTGRES_PASSWORD=hejsan123
      #- POSTGRES_HOST_AUTH_METHOD=trust
  spa:
    image: nginx
    container_name: spa
    ports:
      - "80:80"
    volumes:
      - ./spa/nginx.conf:/etc/nginx/nginx.conf
      - ./spa/static/index.html:/data/www/index.html
      - ./spa/static/js/navigation.js:/data/www/navigation.js
      - ./spa/static/css/bulma.min.css:/data/www/bulma.min.css
      - ./spa/static/css/styles.css:/data/www/styles.css
    